version: "3.7"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: backend-python
    depends_on:
      - es
    restart: always
    volumes:
      - ./backend-python:/app
    stdin_open: true # enable attach for pdb
    tty: true
    ports:
      - "8080:80"

  site:
    build: frontend-react
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend-react:/site
    ports:
      - "8090:80"

volumes:
  esdata:
